rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
gemfile:
  - gemfiles/Gemfile.puppet-2.6
  - gemfiles/Gemfile.puppet-2.7
branches:
  only:
    - master
notifications:
  email:
    - tim@github.com
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.puppet-2.6
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.puppet-2.6
